# .circleci/config.yml
version: 2.1

jobs:
  lambda:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Get Deps
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: 
          name: Test
          command: go test
      - run:
          name: Build
          command: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o "./main" "nrapp"
      - run:
          name: Package
          command: |
            zip -j ./nrapp.zip ./main
      - run:
          name: install awscli
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip 
            sudo pip install awscli
      - run:
          name: Deploy 
          command: |
            aws lambda update-function-code --function-name nrapp --zip-file fileb://./nrapp.zip --region us-west-2

workflows:
  main:
    jobs:
      - lambda