# .circleci/config.yml
version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      # - image: circleci/golang:1.15
      - image: cimg/go:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Get Deps
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: 
          name: Test
          command: go test
      - run:
          name: Build
          command: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o "./main" "nrapp"
      - run:
          name: Package
          command: |
            zip -j ./nrapp.zip ./main
  # deploy:
  #   steps:
  #     - run:
  #         name: Update 
  #         command: |
  #           aws lambda update-function-code --function-name nrapp --zip-file fileb://./main.zip
  #     - run:
  #         name: Deploy 
  #         command: |
  #           aws apigateway create-deployment --rest-api-id vnp5rwu1u8 --stage-name staging

workflows:
  main:
    jobs:
      - build
      # - deploy
      